services:
  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    hostname: spark-master
    user: root
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master --host spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-net

  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    user: root
    depends_on:
      - spark-master
    # O SEGREDO ESTÁ AQUI: O Worker também precisa enxergar os arquivos!
    volumes:
      - ../src:/app/src
      - ${DATA_PATH:-../datasample}:/app/data
      - ./output:/app/output
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077 --cores 4 --memory 4G
    networks:
      - spark-net

  spark-job:
    image: apache/spark:3.5.0
    container_name: spark-job
    user: root
    volumes:
      - ../src:/app/src
      - ${DATA_PATH:-../datasample}:/app/data
      - ./output:/app/output
    depends_on:
      - spark-worker
    command: >
      /opt/spark/bin/spark-submit
      --master spark://spark-master:7077
      /app/src/main.py
      /app/data/${DATA_FILE:-esea_sample.csv}
      /app/output
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge