services:
  spark-master:
    container_name: spark-master
    image: bitnami/spark:4.0.0
    user: root
    command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - ./src:/app/src
      - ./full_data:/app/full_data
      - ./datasample:/app/datasample
    networks:
      - spark-network

  spark-worker:
    container_name: spark-worker
    image: bitnami/spark:4.0.0
    user: root
    command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - ./src:/app/src
      - ./full_data:/app/full_data
      - ./datasample:/app/datasample
    networks:
      - spark-network

  jupyterlab:
    container_name: jupyterlab
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8888:8888" 
      - "8501:8501" 
      - "4040:4040" 
    volumes:
      - ./src:/app/src
      - ./full_data:/app/full_data
      - ./datasample:/app/datasample
    working_dir: /app/src
    depends_on:
      - spark-master
    networks:
      - spark-network
    
networks:
  spark-network:
    driver: bridge