version: '3.8'

services:
  spark-master:
    image: bitnami/spark:3.5
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./spark-data:/spark-data
    networks:
      - spark-net
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 2G

  jupyter:
    image: my-jupyter-spark
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./notebooks:/opt/jupyter/notebooks
      - ./spark-data:/spark-data
    environment:
      - JUPYTER_TOKEN=spark123
    depends_on:
      - spark-master
    networks:
      - spark-net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 3G
    command: >
      jupyter notebook
      --ip=0.0.0.0
      --NotebookApp.token=spark123
      --NotebookApp.notebook_dir=/opt/jupyter
      --no-browser
      --allow-root

  spark-worker:
    image: bitnami/spark:3.5
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark-master
    volumes:
      - ./spark-data:/spark-data
    networks:
      - spark-net
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 1G

volumes:
  spark-data:
    external: true

networks:
  spark-net: